version: "3.8"
services:
    app:
        build: .
        image: lab-docker-node-express
        container_name: lab-docker-node-express
        restart: always
        command: /app/node_modules/.bin/nodemon --exec npm start --ext jade
        networks:
            - lab
        ports:
            - 8001:3000
        volumes: 
            - .:/app
            - node_modules:/app/node_modules
networks:
    lab:
        name: lab

volumes:
    node_modules:
        name: ldne-node-modules