version: "3.8"
networks:
    default:
        name: lab-docker-node-express
services:
    app:
        build: .
        image: lab-docker-node-express
        container_name: lab-docker-node-express
        restart: always
        ports:
            - 8001:3000
        volumes: 
            - ./:/app

